const crypto = require('crypto');
const { run, all, exec, transaction } = require('./relationalSqlite');

// Composite foreign keys prevent a row from connecting two different accounts.
const SCHEMA_SQL = `
CREATE TABLE IF NOT EXISTS schema_migrations (version TEXT PRIMARY KEY, checksum TEXT NOT NULL, applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS migration_quarantine (id INTEGER PRIMARY KEY, source_table TEXT NOT NULL, source_id TEXT, account_id INTEGER, reason TEXT NOT NULL, raw_payload TEXT NOT NULL, suggested_resolution TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, resolved_at TEXT);
CREATE TABLE IF NOT EXISTS accounts (id INTEGER PRIMARY KEY, name TEXT NOT NULL, slug TEXT, active INTEGER NOT NULL DEFAULT 1 CHECK(active IN(0,1)), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(id), UNIQUE(slug));
CREATE TABLE IF NOT EXISTS stores (id INTEGER PRIMARY KEY, account_id INTEGER NOT NULL, name TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, UNIQUE(account_id,id), FOREIGN KEY(account_id) REFERENCES accounts(id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, account_id INTEGER NOT NULL, name TEXT NOT NULL, email TEXT, password_hash TEXT, active INTEGER NOT NULL DEFAULT 1, UNIQUE(account_id,id), UNIQUE(account_id,email), FOREIGN KEY(account_id) REFERENCES accounts(id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS sessions (id TEXT PRIMARY KEY, account_id INTEGER NOT NULL, user_id INTEGER NOT NULL, expires_at TEXT, FOREIGN KEY(account_id,user_id) REFERENCES users(account_id,id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS roles (id INTEGER PRIMARY KEY, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS permissions (id INTEGER PRIMARY KEY, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS role_permissions (role_id INTEGER NOT NULL, permission_id INTEGER NOT NULL, PRIMARY KEY(role_id,permission_id), FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE RESTRICT, FOREIGN KEY(permission_id) REFERENCES permissions(id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS user_roles (account_id INTEGER NOT NULL, user_id INTEGER NOT NULL, role_id INTEGER NOT NULL, PRIMARY KEY(account_id,user_id,role_id), FOREIGN KEY(account_id,user_id) REFERENCES users(account_id,id) ON DELETE RESTRICT, FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS customer_types (id INTEGER PRIMARY KEY, account_id INTEGER NOT NULL, name TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, UNIQUE(account_id,id), UNIQUE(account_id,name), FOREIGN KEY(account_id) REFERENCES accounts(id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS customers (id INTEGER PRIMARY KEY, account_id INTEGER NOT NULL, customer_type_id INTEGER, name TEXT NOT NULL, phone TEXT, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(account_id,id), FOREIGN KEY(account_id) REFERENCES accounts(id) ON DELETE RESTRICT, FOREIGN KEY(account_id,customer_type_id) REFERENCES customer_types(account_id,id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS customer_addresses (id INTEGER PRIMARY KEY, account_id INTEGER NOT NULL, customer_id INTEGER NOT NULL, address TEXT NOT NULL, FOREIGN KEY(account_id,customer_id) REFERENCES customers(account_id,id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS suppliers (id INTEGER PRIMARY KEY, account_id INTEGER NOT NULL, name TEXT NOT NULL, phone TEXT, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(account_id,id), FOREIGN KEY(account_id) REFERENCES accounts(id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS product_categories (id INTEGER PRIMARY KEY, account_id INTEGER NOT NULL, name TEXT NOT NULL, parent_id INTEGER, active INTEGER NOT NULL DEFAULT 1, UNIQUE(account_id,id), UNIQUE(account_id,name), FOREIGN KEY(account_id) REFERENCES accounts(id) ON DELETE RESTRICT, FOREIGN KEY(account_id,parent_id) REFERENCES product_categories(account_id,id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS units (id INTEGER PRIMARY KEY, account_id INTEGER NOT NULL, name TEXT NOT NULL, UNIQUE(account_id,id), UNIQUE(account_id,name), FOREIGN KEY(account_id) REFERENCES accounts(id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS products (id INTEGER PRIMARY KEY, account_id INTEGER NOT NULL, category_id INTEGER, unit_id INTEGER, sku TEXT NOT NULL, sku_normalized TEXT NOT NULL, name TEXT NOT NULL, purchase_price REAL NOT NULL DEFAULT 0 CHECK(purchase_price>=0), sale_price REAL NOT NULL DEFAULT 0 CHECK(sale_price>=0), active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(account_id,id), UNIQUE(account_id,sku_normalized), FOREIGN KEY(account_id) REFERENCES accounts(id) ON DELETE RESTRICT, FOREIGN KEY(account_id,category_id) REFERENCES product_categories(account_id,id) ON DELETE SET NULL, FOREIGN KEY(account_id,unit_id) REFERENCES units(account_id,id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS product_variants (id INTEGER PRIMARY KEY, account_id INTEGER NOT NULL, product_id INTEGER NOT NULL, sku TEXT NOT NULL, sku_normalized TEXT NOT NULL, name TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, UNIQUE(account_id,id), UNIQUE(account_id,sku_normalized), FOREIGN KEY(account_id,product_id) REFERENCES products(account_id,id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS product_barcodes (id INTEGER PRIMARY KEY, account_id INTEGER NOT NULL, product_id INTEGER NOT NULL, barcode TEXT NOT NULL, UNIQUE(account_id,barcode), FOREIGN KEY(account_id,product_id) REFERENCES products(account_id,id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS combos (id INTEGER PRIMARY KEY, account_id INTEGER NOT NULL, name TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, UNIQUE(account_id,id), FOREIGN KEY(account_id) REFERENCES accounts(id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS combo_items (id INTEGER PRIMARY KEY, account_id INTEGER NOT NULL, combo_id INTEGER NOT NULL, product_id INTEGER, variant_id INTEGER, quantity REAL NOT NULL CHECK(quantity>0), CHECK((product_id IS NOT NULL) != (variant_id IS NOT NULL)), FOREIGN KEY(account_id,combo_id) REFERENCES combos(account_id,id) ON DELETE RESTRICT, FOREIGN KEY(account_id,product_id) REFERENCES products(account_id,id) ON DELETE RESTRICT, FOREIGN KEY(account_id,variant_id) REFERENCES product_variants(account_id,id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS warehouses (id INTEGER PRIMARY KEY, account_id INTEGER NOT NULL, name TEXT NOT NULL, allow_negative_stock INTEGER NOT NULL DEFAULT 0 CHECK(allow_negative_stock IN(0,1)), UNIQUE(account_id,id), FOREIGN KEY(account_id) REFERENCES accounts(id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS inventory_balances (account_id INTEGER NOT NULL, warehouse_id INTEGER NOT NULL, product_id INTEGER NOT NULL, quantity REAL NOT NULL DEFAULT 0 CHECK(quantity>=0), PRIMARY KEY(account_id,warehouse_id,product_id), FOREIGN KEY(account_id,warehouse_id) REFERENCES warehouses(account_id,id) ON DELETE RESTRICT, FOREIGN KEY(account_id,product_id) REFERENCES products(account_id,id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS orders (id INTEGER PRIMARY KEY, account_id INTEGER NOT NULL, order_code TEXT NOT NULL COLLATE NOCASE, customer_id INTEGER, created_by INTEGER, status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN('draft','pending','completed','cancelled','returned')), payment_status TEXT NOT NULL DEFAULT 'unpaid' CHECK(payment_status IN('unpaid','partial','paid','refunded','cancelled')), subtotal REAL NOT NULL DEFAULT 0 CHECK(subtotal>=0), discount_amount REAL NOT NULL DEFAULT 0 CHECK(discount_amount>=0), vat_amount REAL NOT NULL DEFAULT 0 CHECK(vat_amount>=0), delivery_fee REAL NOT NULL DEFAULT 0 CHECK(delivery_fee>=0), total_amount REAL NOT NULL DEFAULT 0 CHECK(total_amount>=0), paid_amount REAL NOT NULL DEFAULT 0 CHECK(paid_amount>=0 AND paid_amount<=total_amount), remaining_amount REAL NOT NULL DEFAULT 0 CHECK(remaining_amount=total_amount-paid_amount), payment_method TEXT, note TEXT, idempotency_key TEXT, client_order_id TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, cancelled_at TEXT, UNIQUE(account_id,id), UNIQUE(account_id,order_code), UNIQUE(account_id,idempotency_key), FOREIGN KEY(account_id) REFERENCES accounts(id) ON DELETE RESTRICT, FOREIGN KEY(account_id,customer_id) REFERENCES customers(account_id,id) ON DELETE RESTRICT, FOREIGN KEY(account_id,created_by) REFERENCES users(account_id,id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS order_items (id INTEGER PRIMARY KEY, account_id INTEGER NOT NULL, order_id INTEGER NOT NULL, product_id INTEGER, variant_id INTEGER, product_sku_snapshot TEXT NOT NULL, product_name_snapshot TEXT NOT NULL, unit_snapshot TEXT NOT NULL DEFAULT '', quantity REAL NOT NULL CHECK(quantity>0), purchase_price_snapshot REAL NOT NULL DEFAULT 0 CHECK(purchase_price_snapshot>=0), unit_price REAL NOT NULL CHECK(unit_price>=0), discount_amount REAL NOT NULL DEFAULT 0 CHECK(discount_amount>=0), line_total REAL NOT NULL CHECK(line_total=quantity*unit_price-discount_amount AND line_total>=0), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(account_id,order_id) REFERENCES orders(account_id,id) ON DELETE CASCADE, FOREIGN KEY(account_id,product_id) REFERENCES products(account_id,id) ON DELETE SET NULL, FOREIGN KEY(account_id,variant_id) REFERENCES product_variants(account_id,id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS order_status_history (id INTEGER PRIMARY KEY, account_id INTEGER NOT NULL, order_id INTEGER NOT NULL, old_status TEXT, new_status TEXT NOT NULL, changed_by INTEGER, reason TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(account_id,order_id) REFERENCES orders(account_id,id) ON DELETE RESTRICT, FOREIGN KEY(account_id,changed_by) REFERENCES users(account_id,id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS purchase_receipts (id INTEGER PRIMARY KEY, account_id INTEGER NOT NULL, receipt_code TEXT NOT NULL COLLATE NOCASE, supplier_id INTEGER, created_by INTEGER, status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN('draft','received','cancelled')), total_amount REAL NOT NULL DEFAULT 0 CHECK(total_amount>=0), paid_amount REAL NOT NULL DEFAULT 0 CHECK(paid_amount>=0 AND paid_amount<=total_amount), remaining_amount REAL NOT NULL DEFAULT 0 CHECK(remaining_amount=total_amount-paid_amount), note TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(account_id,id), UNIQUE(account_id,receipt_code), FOREIGN KEY(account_id) REFERENCES accounts(id) ON DELETE RESTRICT, FOREIGN KEY(account_id,supplier_id) REFERENCES suppliers(account_id,id) ON DELETE RESTRICT, FOREIGN KEY(account_id,created_by) REFERENCES users(account_id,id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS purchase_receipt_items (id INTEGER PRIMARY KEY, account_id INTEGER NOT NULL, receipt_id INTEGER NOT NULL, product_id INTEGER, variant_id INTEGER, product_sku_snapshot TEXT NOT NULL, product_name_snapshot TEXT NOT NULL, quantity REAL NOT NULL CHECK(quantity>0), unit_cost REAL NOT NULL CHECK(unit_cost>=0), line_total REAL NOT NULL CHECK(line_total=quantity*unit_cost), FOREIGN KEY(account_id,receipt_id) REFERENCES purchase_receipts(account_id,id) ON DELETE CASCADE, FOREIGN KEY(account_id,product_id) REFERENCES products(account_id,id) ON DELETE SET NULL, FOREIGN KEY(account_id,variant_id) REFERENCES product_variants(account_id,id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS payments (id INTEGER PRIMARY KEY, account_id INTEGER NOT NULL, order_id INTEGER, purchase_receipt_id INTEGER, customer_id INTEGER, supplier_id INTEGER, amount REAL NOT NULL CHECK(amount>0), method TEXT NOT NULL, paid_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, idempotency_key TEXT, UNIQUE(account_id,id), UNIQUE(account_id,idempotency_key), FOREIGN KEY(account_id,order_id) REFERENCES orders(account_id,id) ON DELETE RESTRICT, FOREIGN KEY(account_id,purchase_receipt_id) REFERENCES purchase_receipts(account_id,id) ON DELETE RESTRICT, FOREIGN KEY(account_id,customer_id) REFERENCES customers(account_id,id) ON DELETE RESTRICT, FOREIGN KEY(account_id,supplier_id) REFERENCES suppliers(account_id,id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS customer_debts (id INTEGER PRIMARY KEY, account_id INTEGER NOT NULL, customer_id INTEGER NOT NULL, order_id INTEGER NOT NULL, original_amount REAL NOT NULL CHECK(original_amount>=0), remaining_amount REAL NOT NULL CHECK(remaining_amount>=0), FOREIGN KEY(account_id,customer_id) REFERENCES customers(account_id,id) ON DELETE RESTRICT, FOREIGN KEY(account_id,order_id) REFERENCES orders(account_id,id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS supplier_debts (id INTEGER PRIMARY KEY, account_id INTEGER NOT NULL, supplier_id INTEGER NOT NULL, purchase_receipt_id INTEGER NOT NULL, original_amount REAL NOT NULL CHECK(original_amount>=0), remaining_amount REAL NOT NULL CHECK(remaining_amount>=0), FOREIGN KEY(account_id,supplier_id) REFERENCES suppliers(account_id,id) ON DELETE RESTRICT, FOREIGN KEY(account_id,purchase_receipt_id) REFERENCES purchase_receipts(account_id,id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS cash_accounts (id INTEGER PRIMARY KEY, account_id INTEGER NOT NULL, name TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, UNIQUE(account_id,id), FOREIGN KEY(account_id) REFERENCES accounts(id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS bank_accounts (id INTEGER PRIMARY KEY, account_id INTEGER NOT NULL, name TEXT NOT NULL, account_number TEXT, active INTEGER NOT NULL DEFAULT 1, UNIQUE(account_id,id), FOREIGN KEY(account_id) REFERENCES accounts(id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS cash_ledger (id INTEGER PRIMARY KEY, account_id INTEGER NOT NULL, payment_id INTEGER, cash_account_id INTEGER, bank_account_id INTEGER, direction TEXT NOT NULL CHECK(direction IN('in','out')), amount REAL NOT NULL CHECK(amount>0), reference_type TEXT NOT NULL, reference_id INTEGER NOT NULL, idempotency_key TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(account_id,idempotency_key), FOREIGN KEY(account_id,payment_id) REFERENCES payments(account_id,id) ON DELETE RESTRICT, FOREIGN KEY(account_id,cash_account_id) REFERENCES cash_accounts(account_id,id) ON DELETE RESTRICT, FOREIGN KEY(account_id,bank_account_id) REFERENCES bank_accounts(account_id,id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS inventory_movements (id INTEGER PRIMARY KEY, account_id INTEGER NOT NULL, warehouse_id INTEGER NOT NULL, product_id INTEGER NOT NULL, quantity_delta REAL NOT NULL CHECK(quantity_delta<>0), reference_type TEXT NOT NULL, reference_id INTEGER NOT NULL, idempotency_key TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(account_id,idempotency_key), FOREIGN KEY(account_id,warehouse_id) REFERENCES warehouses(account_id,id) ON DELETE RESTRICT, FOREIGN KEY(account_id,product_id) REFERENCES products(account_id,id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS audit_logs (id INTEGER PRIMARY KEY, account_id INTEGER, user_id INTEGER, action TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT, payload TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TRIGGER IF NOT EXISTS no_inventory_movement_update BEFORE UPDATE ON inventory_movements BEGIN SELECT RAISE(ABORT,'inventory_movements are immutable'); END;
CREATE TRIGGER IF NOT EXISTS no_inventory_movement_delete BEFORE DELETE ON inventory_movements BEGIN SELECT RAISE(ABORT,'inventory_movements are immutable'); END;
CREATE TRIGGER IF NOT EXISTS no_cash_ledger_update BEFORE UPDATE ON cash_ledger BEGIN SELECT RAISE(ABORT,'cash_ledger is immutable'); END;
CREATE TRIGGER IF NOT EXISTS no_cash_ledger_delete BEFORE DELETE ON cash_ledger BEGIN SELECT RAISE(ABORT,'cash_ledger is immutable'); END;
CREATE TRIGGER IF NOT EXISTS no_completed_order_delete BEFORE DELETE ON orders WHEN OLD.status IN('completed','cancelled') BEGIN SELECT RAISE(ABORT,'completed or cancelled orders cannot be deleted'); END;
CREATE TRIGGER IF NOT EXISTS completed_order_insert_requires_item BEFORE INSERT ON orders WHEN NEW.status='completed' BEGIN SELECT RAISE(ABORT,'completed orders must be created as draft then completed after items'); END;
CREATE TRIGGER IF NOT EXISTS completed_order_requires_item BEFORE UPDATE OF status ON orders WHEN NEW.status='completed' AND NOT EXISTS(SELECT 1 FROM order_items WHERE account_id=NEW.account_id AND order_id=NEW.id) BEGIN SELECT RAISE(ABORT,'completed order requires at least one item'); END;
`;

async function migrate(db) {
  await run(db, 'PRAGMA journal_mode = WAL');
  await run(db, 'PRAGMA synchronous = FULL');
  await run(db, 'PRAGMA busy_timeout = 5000');
  await exec(db, 'PRAGMA foreign_keys = ON');
  const enabled = await all(db, 'PRAGMA foreign_keys');
  if (Number(enabled[0]?.foreign_keys) !== 1) throw new Error('SQLite foreign keys are disabled');
  const checksum = crypto.createHash('sha256').update(SCHEMA_SQL).digest('hex');
  await transaction(db, async tx => {
    await exec(db, SCHEMA_SQL);
    await tx.run('INSERT INTO schema_migrations(version, checksum) VALUES(?,?) ON CONFLICT(version) DO UPDATE SET checksum=excluded.checksum', ['relational-001', checksum]);
  });
  const foreignKeys = await all(db, 'PRAGMA foreign_key_check');
  const integrity = await all(db, 'PRAGMA integrity_check');
  // sql.js may clear connection pragmas after diagnostic PRAGMAs, so restore
  // foreign-key enforcement as the final connection operation. Do not query
  // another PRAGMA afterward because that can clear the setting again.
  await run(db, 'PRAGMA foreign_keys = ON');
  return { version: 'relational-001', checksum, foreignKeys, integrity };
}

module.exports = { migrate, SCHEMA_SQL };
