const now = new Date().toISOString();

export const mockInvoicePayload = Object.freeze({
  store: {
    name: 'CỬA HÀNG VẠN KHA',
    address: '123 Đường Nguyễn Trãi, Phường 1, Quận 5, TP. Hồ Chí Minh',
    phone: '0909 123 456',
    email: 'contact@vankha.local',
    tax_code: '0312345678',
    logo_url: '',
  },
  customer: {
    name: 'Nguyễn Văn An',
    phone: '0988 000 111',
    address: '45 Lê Lợi, TP. Thủ Đức, TP. Hồ Chí Minh',
    tax_code: '',
  },
  invoice: {
    id: 1001,
    invoice_code: 'HD-20260601-0001',
    created_at: now,
    delivery_date: '01/06/2026',
    status: 'Đã thanh toán',
    payment_method: 'Chuyển khoản',
    note: 'Hàng giao trong giờ hành chính. Vui lòng kiểm tra hàng trước khi nhận.',
  },
  items: [
    {
      id: 1,
      sku: 'SP001',
      name: 'Cà phê rang xay đặc biệt túi 500g tên dài để kiểm tra tự xuống dòng khi in hóa đơn',
      unit: 'Túi',
      quantity: 2,
      unit_price: 125000,
      discount_amount: 10000,
      line_total: 240000,
    },
    {
      id: 2,
      sku: 'SP002',
      name: 'Trà sen vàng cao cấp',
      unit: 'Hộp',
      quantity: 1,
      unit_price: 180000,
      discount_amount: 0,
      line_total: 180000,
    },
    {
      id: 3,
      sku: 'SP003',
      name: 'Bánh quy bơ nhập khẩu',
      unit: 'Gói',
      quantity: 3,
      unit_price: 45000,
      discount_amount: 5000,
      line_total: 130000,
    },
    {
      id: 4,
      sku: 'SP004',
      name: 'Combo quà tặng doanh nghiệp',
      unit: 'Bộ',
      quantity: 1,
      unit_price: 320000,
      discount_amount: 20000,
      line_total: 300000,
    },
  ],
  totals: {
    subtotal: 870000,
    vat_percent: 0,
    vat_amount: 0,
    discount_amount: 35000,
    delivery_fee: 25000,
    total: 860000,
    paid_amount: 500000,
    remaining_amount: 360000,
    change_amount: 0,
  },
  payment: {
    method_label: 'Chuyển khoản',
    bank_name: 'Vietcombank',
    bank_account: '0123456789',
    bank_account_name: 'CUA HANG VAN KHA',
    transfer_content: 'HD-20260601-0001',
    qr_text: 'Quét QR để thanh toán nhanh',
    qr_image: '',
  },
  signatures: {
    buyer: { label: 'Người nhận hàng', name: 'Nguyễn Văn An' },
    seller: { label: 'Người viết hóa đơn', name: 'Thu ngân' },
  },
  metadata: {
    user_name: 'Thu ngân',
    printed_at: now,
  },
});

export default mockInvoicePayload;
